import { BadgeCheck, HeartPulse, PawPrint, ShieldCheck } from "lucide-react";
import Link from "next/link";
import { notFound, redirect } from "next/navigation";

import { PortalShell } from "@/components/portal/portal-shell";
import { buttonVariants } from "@/components/ui/button";
import { prisma } from "@/lib/db";
import { getCurrentIdentity } from "@/modules/auth/session";

export default async function DigitalPetIdPage({ params }: { params: Promise<{ id: string }> }) {
  const identity = await getCurrentIdentity(); const { id } = await params;
  if (!identity?.roles.includes("CUSTOMER")) redirect(`/login?returnTo=/pets/${id}/id-card`);
  const pet = await prisma.pet.findFirst({ where: { id, ownerId: identity.id, active: true }, include: { medicalProfile: true, emergencyContacts: { orderBy: { priority: "asc" }, take: 1 }, _count: { select: { vaccinations: true, medications: true, healthEvents: true } } } });
  if (!pet) notFound();
  const code = pet.id.replaceAll("-", "").slice(0, 16).toUpperCase();
  return <PortalShell mode="customer" displayName={identity.displayName} metrics={[`${pet._count.vaccinations} vaccinations`, `${pet._count.medications} medications`, `${pet._count.healthEvents} health events`]}><div className="mx-auto mt-5 max-w-4xl"><section className="relative overflow-hidden rounded-[3rem] bg-[#2f2032] p-7 text-paper shadow-soft sm:p-10"><div className="absolute -right-16 -top-20 h-72 w-72 rounded-full bg-coral/25 blur-3xl" /><div className="relative flex flex-col justify-between gap-10 sm:flex-row"><div><p className="text-[0.62rem] font-bold uppercase tracking-[0.22em] text-saffron">PetSaathi digital pet ID</p><h1 className="mt-5 font-display text-6xl font-semibold tracking-[-0.055em]">{pet.name}</h1><p className="mt-3 text-paper/58">{pet.species.toLowerCase()}{pet.breed ? ` · ${pet.breed}` : ""}{pet.weightKg ? ` · ${pet.weightKg.toString()} kg` : ""}</p><div className="mt-7 flex flex-wrap gap-2"><span className="flex items-center gap-2 rounded-full bg-paper/10 px-3 py-2 text-xs font-bold"><ShieldCheck className="h-4 w-4 text-saffron" />Private owner record</span><span className="flex items-center gap-2 rounded-full bg-paper/10 px-3 py-2 text-xs font-bold"><BadgeCheck className="h-4 w-4 text-saffron" />Active profile</span></div></div><span className="flex h-32 w-32 shrink-0 items-center justify-center rounded-[2.3rem] border border-paper/15 bg-paper/10"><PawPrint className="h-14 w-14 text-saffron" strokeWidth={1.4} /></span></div><div className="relative mt-10 grid gap-3 border-t border-paper/10 pt-6 sm:grid-cols-3"><div><p className="text-[0.6rem] font-bold uppercase tracking-[0.16em] text-paper/35">Pet ID</p><p className="mt-2 font-mono text-sm tracking-[0.15em]">{code}</p></div><div><p className="text-[0.6rem] font-bold uppercase tracking-[0.16em] text-paper/35">Emergency contact</p><p className="mt-2 text-sm font-bold">{pet.emergencyContacts[0]?.name ?? "Not recorded"}</p></div><div><p className="text-[0.6rem] font-bold uppercase tracking-[0.16em] text-paper/35">Medical snapshot</p><p className="mt-2 flex items-center gap-2 text-sm font-bold"><HeartPulse className="h-4 w-4 text-coral" />{pet.medicalProfile ? "Available" : "Not recorded"}</p></div></div></section><div className="mt-5 flex flex-col items-start justify-between gap-4 rounded-4xl border border-indigo/10 bg-paper p-6 shadow-lifted sm:flex-row sm:items-center"><p className="max-w-xl text-sm leading-6 text-ink/50">This card is an authenticated convenience view. It is not a government identity document, vaccination certificate or substitute for veterinary records.</p><Link href={`/pets/${pet.id}`} className={buttonVariants({ variant: "outline" })}>Open full passport</Link></div></div></PortalShell>;
}
