import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
          // Legacy colors required by existing components
          "cream": "rgb(var(--cream) / <alpha-value>)",
          "paper": "rgb(var(--paper) / <alpha-value>)",
          "ink": "rgb(var(--ink) / <alpha-value>)",
          "saffron": "rgb(var(--saffron) / <alpha-value>)",
          "coral": "rgb(var(--coral) / <alpha-value>)",
          "coral-text": "rgb(var(--coral-text) / <alpha-value>)",
          "indigo": "rgb(var(--indigo) / <alpha-value>)",
          "leaf": "rgb(var(--leaf) / <alpha-value>)",

          // Stitch MD3 custom tokens
          "on-secondary-fixed-variant": "#85230c",
          "background": "#fff7fa",
          "secondary-container": "#ff7d5e",
          "surface": "#fff7fa",
          "tertiary-fixed-dim": "#96d3b6",
          "on-primary": "#ffffff",
          "on-background": "#261626",
          "tertiary-fixed": "#b2f0d2",
          "secondary": "#a53b22",
          "surface-container-low": "#ffeffa",
          "tertiary-container": "#16553f",
          "on-tertiary": "#ffffff",
          "on-error": "#ffffff",
          "inverse-primary": "#dcb8ff",
          "surface-container-high": "#fce0f8",
          "inverse-surface": "#3c2a3c",
          "on-tertiary-container": "#8bc8ab",
          "on-secondary": "#ffffff",
          "surface-container": "#ffe7fa",
          "error": "#ba1a1a",
          "tertiary": "#003d2a",
          "surface-tint": "#70518f",
          "surface-bright": "#fff7fa",
          "outline-variant": "#cdc3d0",
          "on-tertiary-fixed-variant": "#10513b",
          "error-container": "#ffdad6",
          "secondary-fixed": "#ffdad2",
          "on-secondary-container": "#721501",
          "surface-container-highest": "#f6daf2",
          "on-primary-fixed": "#290947",
          "on-surface-variant": "#4b454f",
          "on-error-container": "#93000a",
          "primary-container": "#5b3d7a",
          "on-secondary-fixed": "#3d0700",
          "primary-fixed-dim": "#dcb8ff",
          "on-primary-container": "#d0acf2",
          "surface-variant": "#f6daf2",
          "secondary-fixed-dim": "#ffb4a3",
          "on-surface": "#261626",
          "primary-fixed": "#f0dbff",
          "primary": "#432662",
          "surface-dim": "#edd2e9",
          "on-primary-fixed-variant": "#573976",
          "outline": "#7c7480",
          "on-tertiary-fixed": "#002115",
          "surface-container-lowest": "#ffffff",
          "inverse-on-surface": "#ffebfa"
      },
      "borderRadius": {
          "DEFAULT": "0.25rem",
          "lg": "0.5rem",
          "xl": "0.75rem",
          "2xl": "1rem",
          "3xl": "1.5rem",
          "4xl": "2rem",
          "5xl": "2.75rem",
          "full": "9999px"
      },
      "boxShadow": {
        "soft": "0 24px 80px -34px rgba(55, 28, 67, 0.25)",
        "lifted": "0 18px 44px -24px rgba(55, 28, 67, 0.28)",
        "glow": "0 0 0 1px rgba(91, 61, 122, 0.06), 0 22px 70px -34px rgba(238, 116, 83, 0.4)",
        "card-shadow": "0px 10px 30px rgba(48, 31, 48, 0.05)"
      },
      "spacing": {
          "margin-mobile": "16px",
          "stack_sm": "8px",
          "stack_md": "16px",
          "stack_lg": "24px",
          "container_padding": "32px",
          "gutter": "24px",
          "sidebar-width": "260px",
          "base": "8px",
          "margin-desktop": "40px",
          "container-max": "1440px"
      },
      "fontFamily": {
          "body-sm": ["var(--font-inter)", "Inter", "sans-serif"],
          "title-md": ["var(--font-inter)", "Inter", "sans-serif"],
          "label-caps": ["var(--font-inter)", "Inter", "sans-serif"],
          "body-md": ["var(--font-inter)", "Inter", "sans-serif"],
          "body-lg": ["var(--font-inter)", "Inter", "sans-serif"],
          "headline-lg-mobile": ["var(--font-hanken)", "Hanken Grotesk", "sans-serif"],
          "headline-lg": ["var(--font-hanken)", "Hanken Grotesk", "sans-serif"],
          "headline-md": ["var(--font-hanken)", "Hanken Grotesk", "sans-serif"],
          "title-lg": ["var(--font-inter)", "Inter", "sans-serif"],
          "label-md": ["var(--font-inter)", "Inter", "sans-serif"],
          "display-lg": ["var(--font-hanken)", "Hanken Grotesk", "sans-serif"],
          "display": ["var(--font-hanken)", "Hanken Grotesk", "sans-serif"],
          "sans": ["var(--font-inter)", "Inter", "sans-serif"],
      },
      "fontSize": {
          "body-sm": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
          "title-md": ["20px", { "lineHeight": "28px", "fontWeight": "600" }],
          "label-caps": ["12px", { "lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "600" }],
          "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
          "body-lg": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
          "headline-lg-mobile": ["24px", { "lineHeight": "32px", "fontWeight": "600" }],
          "headline-lg": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
          "headline-md": ["24px", { "lineHeight": "32px", "fontWeight": "600" }],
          "title-lg": ["20px", { "lineHeight": "28px", "fontWeight": "600" }],
          "label-md": ["12px", { "lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "600" }],
          "display-lg": ["48px", { "lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700" }]
      }
    },
  },
  plugins: [],
};
export default config;


