import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
        "cream": "rgb(var(--cream) / <alpha-value>)",
        "paper": "rgb(var(--paper) / <alpha-value>)",
        "ink": "rgb(var(--ink) / <alpha-value>)",
        "saffron": "rgb(var(--saffron) / <alpha-value>)",
        "coral": "rgb(var(--coral) / <alpha-value>)",
        "indigo": "rgb(var(--indigo) / <alpha-value>)",
        "leaf": "rgb(var(--leaf) / <alpha-value>)",
        "outline": "#747878",
        "primary": "#000000",
        "secondary-container": "#e5e2dd",
        "surface-container": "#f6ece3",
        "surface-bright": "#fff8f3",
        "on-primary-fixed": "#1c1b1b",
        "surface-tint": "#5f5e5e",
        "on-primary-fixed-variant": "#474746",
        "surface-container-lowest": "#ffffff",
        "on-secondary-fixed-variant": "#474743",
        "on-tertiary-fixed-variant": "#78310c",
        "on-background": "#1f1b15",
        "surface-container-low": "#fcf2e8",
        "on-tertiary-container": "#c56c43",
        "surface-dim": "#e2d9cf",
        "on-surface": "#1f1b15",
        "background": "#fff8f3",
        "on-primary": "#ffffff",
        "outline-variant": "#c4c7c7",
        "primary-fixed": "#e5e2e1",
        "surface-variant": "#eae1d8",
        "tertiary-container": "#360f00",
        "on-secondary-container": "#656461",
        "on-secondary": "#ffffff",
        "on-error-container": "#93000a",
        "secondary": "#5f5e5b",
        "tertiary": "#000000",
        "on-secondary-fixed": "#1c1c19",
        "primary-container": "#1c1b1b",
        "surface-container-high": "#f0e7dd",
        "inverse-surface": "#343029",
        "tertiary-fixed": "#ffdbcd",
        "tertiary-fixed-dim": "#ffb597",
        "on-tertiary-fixed": "#360f00",
        "surface": "#fff8f3",
        "inverse-on-surface": "#f9efe6",
        "on-surface-variant": "#444748",
        "error": "#ba1a1a",
        "secondary-fixed-dim": "#c9c6c2",
        "on-primary-container": "#858383",
        "inverse-primary": "#c8c6c5",
        "on-tertiary": "#ffffff",
        "secondary-fixed": "#e5e2dd",
        "surface-container-highest": "#eae1d8",
        "error-container": "#ffdad6",
        "primary-fixed-dim": "#c8c6c5",
        "on-error": "#ffffff"
      },
      "borderRadius": {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        "4xl": "2rem",
        "5xl": "2.75rem",
        "full": "9999px"
      },
      "boxShadow": {
        "soft": "0 24px 80px -34px rgba(55, 28, 67, 0.25)",
        "lifted": "0 18px 44px -24px rgba(55, 28, 67, 0.28)",
        "glow": "0 0 0 1px rgba(91, 61, 122, 0.06), 0 22px 70px -34px rgba(238, 116, 83, 0.4)"
      },
      "spacing": {
        "section-gap": "120px",
        "base-unit": "8px",
        "gutter": "24px",
        "margin-mobile": "20px",
        "container-max": "1280px",
        "margin-desktop": "64px",
        "stack-sm": "32px",
        "stack-md": "64px",
        "stack-lg": "120px",
        "stack-xl": "160px"
      },
      "fontFamily": {
        "display": ["var(--font-playfair)", "Georgia", "serif"],
        "sans": ["var(--font-manrope)", "var(--font-inter)", "sans-serif"],
        "display-lg": ["var(--font-playfair)", "serif"],
        "label-sm": ["var(--font-inter)", "sans-serif"],
        "headline-md": ["var(--font-playfair)", "serif"],
        "body-lg": ["var(--font-inter)", "sans-serif"],
        "display-lg-mobile": ["var(--font-playfair)", "serif"],
        "body-md": ["var(--font-inter)", "sans-serif"]
      },
      "fontSize": {
        "display-lg": ["64px", {"lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "label-sm": ["12px", {"lineHeight": "1.0", "letterSpacing": "0.05em", "fontWeight": "600"}],
        "headline-md": ["32px", {"lineHeight": "1.3", "fontWeight": "600"}],
        "body-lg": ["18px", {"lineHeight": "1.6", "fontWeight": "400"}],
        "display-lg-mobile": ["40px", {"lineHeight": "1.2", "fontWeight": "700"}],
        "body-md": ["16px", {"lineHeight": "1.6", "fontWeight": "400"}]
      }
    },
  },
  plugins: [],
};
export default config;
