"use client";

import { LoaderCircle, MapPinned, Plus, SlidersHorizontal, WalletCards } from "lucide-react";
import { useRouter } from "next/navigation";
import { useState, type FormEvent } from "react";

type Service = { code: string; name: string; active: boolean };
type Area = { id: string; name: string; status: string; city: string; state: string; postalCodes: string[] };
type Price = { id: string; serviceName: string; areaName: string; version: number; amountPaise: number; sitterPaise: number; taxBasisPoints: number; effectiveAt: string; expiresAt: string | null };
type Capacity = { id: string; areaName: string; serviceCode: string; serviceDate: string; maximum: number; reserved: number; reason: string | null };
type ApiResult = { message?: string; error?: string; issues?: unknown };

export function CatalogAdmin({ services, areas, prices, capacities, canManageAreas, canManagePrices, canManageCapacity }: { services: Service[]; areas: Area[]; prices: Price[]; capacities: Capacity[]; canManageAreas: boolean; canManagePrices: boolean; canManageCapacity: boolean }) {
  return <div className="mt-10 grid gap-8">
    <div className="grid gap-6 xl:grid-cols-3">{canManageAreas && <AreaForm />}{canManagePrices && <PriceForm services={services} areas={areas.filter(({ status }) => status === "ACTIVE")} />}{canManageCapacity && <CapacityForm services={services.filter(({ active }) => active)} areas={areas.filter(({ status }) => status === "ACTIVE")} />}</div>
    <section><SectionHeading icon={MapPinned} title="Service areas" hint="City status, postal-code scope and booking eligibility" /><div className="mt-4 grid gap-3 md:grid-cols-2 xl:grid-cols-3">{areas.length ? areas.map((area) => <article key={area.id} className="rounded-3xl border border-ink/10 bg-paper p-5"><div className="flex justify-between gap-3"><h3 className="font-display text-2xl font-semibold">{area.name}</h3><Status value={area.status} /></div><p className="mt-2 text-sm text-ink/55">{area.city}, {area.state}</p><p className="mt-3 text-xs leading-5 text-ink/45">PIN {area.postalCodes.join(", ")}</p></article>) : <Empty label="No service area has been configured." />}</div></section>
    <section><SectionHeading icon={WalletCards} title="Immutable price versions" hint="Latest effective area-specific version wins; otherwise the global version applies" /><div className="mt-4 overflow-x-auto rounded-3xl border border-ink/10 bg-paper"><table className="w-full min-w-[760px] text-left text-sm"><thead className="bg-cream/60 text-xs uppercase tracking-[0.12em] text-ink/45"><tr><th className="p-4">Service</th><th className="p-4">Scope</th><th className="p-4">Version</th><th className="p-4">Customer subtotal</th><th className="p-4">Saathi</th><th className="p-4">Tax</th><th className="p-4">Effective</th></tr></thead><tbody>{prices.map((price) => <tr key={price.id} className="border-t border-ink/8"><td className="p-4 font-semibold">{price.serviceName}</td><td className="p-4">{price.areaName}</td><td className="p-4">v{price.version}</td><td className="p-4">₹{(price.amountPaise / 100).toLocaleString("en-IN")}</td><td className="p-4">₹{(price.sitterPaise / 100).toLocaleString("en-IN")}</td><td className="p-4">{(price.taxBasisPoints / 100).toFixed(2)}%</td><td className="p-4">{new Date(price.effectiveAt).toLocaleString("en-IN")}{price.expiresAt ? ` → ${new Date(price.expiresAt).toLocaleString("en-IN")}` : ""}</td></tr>)}</tbody></table>{!prices.length && <Empty label="No approved price version exists. Customer booking remains closed." />}</div></section>
    <section><SectionHeading icon={SlidersHorizontal} title="Capacity calendar" hint="Reservations can never exceed an approved area, service and India-date maximum" /><div className="mt-4 grid gap-3 md:grid-cols-2 xl:grid-cols-3">{capacities.length ? capacities.map((capacity) => <article key={capacity.id} className="rounded-3xl border border-ink/10 bg-paper p-5"><div className="flex justify-between gap-3"><h3 className="font-semibold">{capacity.areaName}</h3><span className="text-xs font-bold text-indigo">{capacity.serviceDate}</span></div><p className="mt-2 text-sm text-ink/55">{capacity.serviceCode.replaceAll("_", " ")}</p><p className="mt-4 font-display text-3xl font-semibold">{capacity.reserved} / {capacity.maximum}</p><p className="mt-1 text-xs text-ink/45">reserved / approved</p>{capacity.reason && <p className="mt-3 text-xs leading-5 text-ink/50">{capacity.reason}</p>}</article>) : <Empty label="No future service day has been opened." />}</div></section>
  </div>;
}

function AreaForm() {
  const router = useRouter();
  const [pending, setPending] = useState(false); const [message, setMessage] = useState<string | null>(null);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); setPending(true); setMessage(null); const result = await post("/api/admin/service-areas", { cityName: form.get("cityName"), state: form.get("state"), localityName: form.get("localityName"), postalCodes: String(form.get("postalCodes") ?? "").split(",").map((value) => value.trim()).filter(Boolean), status: form.get("status"), reason: form.get("reason") }); setPending(false); setMessage(result.message); if (result.ok) { event.currentTarget.reset(); router.refresh(); } }
  return <AdminForm icon={MapPinned} title="Configure service area" description="Super Admin only. Postal codes cannot overlap within a city." onSubmit={submit} pending={pending} message={message}><Input name="cityName" label="City" required /><Input name="state" label="State" required /><Input name="localityName" label="Locality / area" required /><Input name="postalCodes" label="PIN codes (comma separated)" placeholder="380001, 380015" required /><Select name="status" label="Gate status" options={[{ value: "DRAFT", label: "Draft" }, { value: "ACTIVE", label: "Active" }]} /><Input name="reason" label="Approval reason" minLength={5} required /></AdminForm>;
}

function PriceForm({ services, areas }: { services: Service[]; areas: Area[] }) {
  const router = useRouter(); const [pending, setPending] = useState(false); const [message, setMessage] = useState<string | null>(null);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); const area = String(form.get("serviceAreaId") ?? ""); const expiry = String(form.get("expiresAt") ?? ""); setPending(true); setMessage(null); const result = await post("/api/admin/service-prices", { serviceCode: form.get("serviceCode"), serviceAreaId: area || null, amountPaise: toPaise(form.get("customerAmount")), sitterPaise: toPaise(form.get("sitterAmount")), taxBasisPoints: Math.round(Number(form.get("taxPercent")) * 100), effectiveAt: toIso(form.get("effectiveAt")), expiresAt: expiry ? toIso(expiry) : null, reason: form.get("reason") }); setPending(false); setMessage(result.message); if (result.ok) { event.currentTarget.reset(); router.refresh(); } }
  return <AdminForm icon={WalletCards} title="Approve price version" description="Finance only. Every submission creates a new immutable version." onSubmit={submit} pending={pending} message={message}><Select name="serviceCode" label="Service" options={services.map(({ code, name }) => ({ value: code, label: name }))} /><Select name="serviceAreaId" label="Scope" options={[{ value: "", label: "Global fallback" }, ...areas.map((area) => ({ value: area.id, label: `${area.name}, ${area.city}` }))]} /><Input name="customerAmount" label="Customer subtotal (₹)" type="number" min="0" step="0.01" required /><Input name="sitterAmount" label="Saathi amount (₹)" type="number" min="0" step="0.01" required /><Input name="taxPercent" label="Tax (%)" type="number" min="0" max="100" step="0.01" required /><Input name="effectiveAt" label="Effective from" type="datetime-local" required /><Input name="expiresAt" label="Expires (optional)" type="datetime-local" /><Input name="reason" label="Approval reason" minLength={5} required /></AdminForm>;
}

function CapacityForm({ services, areas }: { services: Service[]; areas: Area[] }) {
  const router = useRouter(); const [pending, setPending] = useState(false); const [message, setMessage] = useState<string | null>(null);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); setPending(true); setMessage(null); const result = await post("/api/admin/capacity-limits", { serviceAreaId: form.get("serviceAreaId"), serviceCode: form.get("serviceCode"), serviceDate: form.get("serviceDate"), maximum: Number(form.get("maximum")), reason: form.get("reason") }); setPending(false); setMessage(result.message); if (result.ok) { event.currentTarget.reset(); router.refresh(); } }
  return <AdminForm icon={SlidersHorizontal} title="Open service capacity" description="Operations only. Use zero to close an unreserved day; the maximum cannot fall below held reservations." onSubmit={submit} pending={pending} message={message}><Select name="serviceAreaId" label="Active area" options={areas.map((area) => ({ value: area.id, label: `${area.name}, ${area.city}` }))} /><Select name="serviceCode" label="Active service" options={services.map(({ code, name }) => ({ value: code, label: name }))} /><Input name="serviceDate" label="India service date" type="date" required /><Input name="maximum" label="Approved bookings" type="number" min="0" max="10000" required /><Input name="reason" label="Operating reason" minLength={5} required /></AdminForm>;
}

function AdminForm({ icon: Icon, title, description, onSubmit, pending, message, children }: { icon: typeof MapPinned; title: string; description: string; onSubmit: (event: FormEvent<HTMLFormElement>) => void; pending: boolean; message: string | null; children: React.ReactNode }) { return <form onSubmit={onSubmit} className="rounded-4xl border border-ink/10 bg-paper p-6 shadow-lifted"><span className="flex h-11 w-11 items-center justify-center rounded-2xl bg-indigo text-paper"><Icon className="h-5 w-5" /></span><h2 className="mt-5 font-display text-3xl font-semibold">{title}</h2><p className="mt-2 text-sm leading-6 text-ink/55">{description}</p><div className="mt-5 grid gap-4">{children}</div><button type="submit" disabled={pending} className="mt-5 flex items-center gap-2 rounded-full bg-ink px-5 py-3 text-sm font-bold text-paper disabled:opacity-45">{pending ? <LoaderCircle className="h-4 w-4 animate-spin" /> : <Plus className="h-4 w-4" />}Save controlled record</button>{message && <p role="status" className="mt-3 text-sm font-semibold text-coral">{message}</p>}</form>; }
function Input(props: React.InputHTMLAttributes<HTMLInputElement> & { label: string }) { const { label, ...rest } = props; return <label className="text-sm font-semibold">{label}<input {...rest} name={rest.name} className="mt-2 min-h-11 w-full rounded-xl border border-ink/12 bg-cream/30 px-3 py-2 font-normal outline-none focus:border-indigo" /></label>; }
function Select({ name, label, options }: { name: string; label: string; options: Array<{ value: string; label: string }> }) { return <label className="text-sm font-semibold">{label}<select name={name} required className="mt-2 min-h-11 w-full rounded-xl border border-ink/12 bg-cream/30 px-3 py-2 font-normal outline-none focus:border-indigo">{options.map((option) => <option key={`${name}-${option.value}`} value={option.value}>{option.label}</option>)}</select></label>; }
function SectionHeading({ icon: Icon, title, hint }: { icon: typeof MapPinned; title: string; hint: string }) { return <div className="flex items-center gap-3"><span className="flex h-11 w-11 items-center justify-center rounded-2xl bg-indigo text-paper"><Icon className="h-5 w-5" /></span><div><h2 className="font-display text-3xl font-semibold">{title}</h2><p className="text-sm text-ink/50">{hint}</p></div></div>; }
function Status({ value }: { value: string }) { return <span className="h-fit rounded-full bg-leaf/10 px-3 py-1 text-xs font-bold text-leaf">{value}</span>; }
function Empty({ label }: { label: string }) { return <div className="rounded-3xl border border-dashed border-ink/15 bg-paper/50 p-7 text-center text-sm font-semibold text-ink/45">{label}</div>; }
function toPaise(value: FormDataEntryValue | null) { return Math.round(Number(value) * 100); }
function toIso(value: FormDataEntryValue | string | null) { const date = new Date(String(value ?? "")); return Number.isNaN(date.getTime()) ? "invalid" : date.toISOString(); }
async function post(url: string, body: unknown) { try { const response = await fetch(url, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); const result = await response.json().catch(() => null) as ApiResult | null; return { ok: response.ok, message: response.ok ? "Saved and audit logged." : result?.message ?? result?.error ?? "The controlled record could not be saved." }; } catch { return { ok: false, message: "The server could not be reached." }; } }
