/**
 * Model Metadata Registry for NVIDIA Phase 3
 * This holds known good metadata. 
 * The system discovers actual availability dynamically via GET /v1/models.
 */

export const capabilityRegistry = [
  {
    id: "nvidia/llama-nemotron-embed-1b-v2",
    provider: "nvidia",
    capabilities: ["embeddings"],
    modalities: ["text"],
    priority: 1,
    enabled: true,
    contextSize: 4096,
    reasoningLevel: 0,
    codingLevel: 0,
    visionLevel: 0,
    speedLevel: 10,
    reliabilityScore: 9,
    costTier: 1,
    supportsTools: false,
    supportsStreaming: false
  },
  {
    id: "nvidia/llama-nemotron-embed-vl-1b-v2",
    provider: "nvidia",
    capabilities: ["embeddings"],
    modalities: ["text", "image"],
    priority: 2,
    enabled: true,
    contextSize: 4096,
    reasoningLevel: 0,
    codingLevel: 0,
    visionLevel: 5,
    speedLevel: 9,
    reliabilityScore: 9,
    costTier: 2,
    supportsTools: false,
    supportsStreaming: false
  },
  {
    id: "nvidia/llama-nemotron-rerank-1b-v2",
    provider: "nvidia",
    capabilities: ["reranking"],
    modalities: ["text"],
    priority: 1,
    enabled: true,
    contextSize: 4096,
    reasoningLevel: 0,
    codingLevel: 0,
    visionLevel: 0,
    speedLevel: 10,
    reliabilityScore: 9,
    costTier: 1,
    supportsTools: false,
    supportsStreaming: false
  },
  {
    id: "nvidia/llama-nemotron-rerank-vl-1b-v2",
    provider: "nvidia",
    capabilities: ["reranking"],
    modalities: ["text", "image"],
    priority: 2,
    enabled: true,
    contextSize: 4096,
    reasoningLevel: 0,
    codingLevel: 0,
    visionLevel: 5,
    speedLevel: 9,
    reliabilityScore: 9,
    costTier: 2,
    supportsTools: false,
    supportsStreaming: false
  },
  {
    id: "nvidia/llama-3.1-nemotron-70b-instruct",
    provider: "nvidia",
    capabilities: ["reasoning", "coding", "fast", "general"],
    modalities: ["text"],
    priority: 1,
    enabled: false,
    contextSize: 128000,
    reasoningLevel: 8,
    codingLevel: 8,
    visionLevel: 0,
    speedLevel: 5,
    reliabilityScore: 9,
    costTier: 2,
    supportsTools: true,
    supportsParallelToolCalls: true,
    supportsStreaming: true
  },
  {
    id: "meta/llama-3.1-70b-instruct",
    provider: "nvidia",
    capabilities: ["reasoning", "coding", "general"],
    modalities: ["text"],
    priority: 2,
    enabled: false,
    contextSize: 128000,
    reasoningLevel: 7,
    codingLevel: 7,
    visionLevel: 0,
    speedLevel: 5,
    reliabilityScore: 9,
    costTier: 2,
    supportsTools: true,
    supportsParallelToolCalls: true,
    supportsStreaming: true
  },
  {
    id: "ibm/granite-34b-code-instruct",
    provider: "nvidia",
    capabilities: ["coding", "fast"],
    modalities: ["text"],
    priority: 2,
    enabled: false,
    contextSize: 8192,
    reasoningLevel: 5,
    codingLevel: 8,
    visionLevel: 0,
    speedLevel: 6,
    reliabilityScore: 8,
    costTier: 1,
    supportsTools: false,
    supportsStreaming: true
  },
  {
    id: "meta/llama-3.1-8b-instruct",
    provider: "nvidia",
    capabilities: ["fast", "general", "coding"],
    modalities: ["text"],
    priority: 1,
    enabled: true,
    contextSize: 128000,
    reasoningLevel: 5,
    codingLevel: 7,
    visionLevel: 0,
    speedLevel: 9,
    reliabilityScore: 9,
    costTier: 1,
    supportsTools: true,
    supportsParallelToolCalls: false,
    supportsStreaming: true
  },
  {
    id: "meta/llama-3.2-1b-instruct",
    provider: "nvidia",
    capabilities: ["fast", "general"],
    modalities: ["text"],
    priority: 2,
    enabled: true,
    contextSize: 128000,
    reasoningLevel: 3,
    codingLevel: 3,
    visionLevel: 0,
    speedLevel: 10,
    reliabilityScore: 8,
    costTier: 1,
    supportsTools: false,
    supportsStreaming: true
  },
  {
    id: "meta/llama-3.2-90b-vision-instruct",
    provider: "nvidia",
    capabilities: ["vision", "multimodal", "reasoning"],
    modalities: ["text", "image"],
    priority: 1,
    enabled: true,
    contextSize: 128000,
    reasoningLevel: 8,
    codingLevel: 6,
    visionLevel: 9,
    speedLevel: 4,
    reliabilityScore: 9,
    costTier: 3,
    supportsTools: true,
    supportsParallelToolCalls: true,
    supportsStreaming: true
  },
  {
    id: "nvidia/vila",
    provider: "nvidia",
    capabilities: ["vision", "multimodal"],
    modalities: ["text", "image"],
    priority: 2,
    enabled: true,
    contextSize: 4096,
    reasoningLevel: 6,
    codingLevel: 4,
    visionLevel: 8,
    speedLevel: 6,
    reliabilityScore: 8,
    costTier: 2,
    supportsTools: false,
    supportsStreaming: true
  },
  // Fake models for fallback testing
  {
    id: "fake-unavailable-vision-model",
    provider: "nvidia",
    capabilities: ["vision", "test-fallback"],
    modalities: ["text", "image"],
    priority: 1,
    enabled: true,
    contextSize: 4096,
    reasoningLevel: 5,
    codingLevel: 5,
    visionLevel: 9,
    speedLevel: 5,
    reliabilityScore: 5,
    costTier: 1,
    supportsTools: false,
    supportsStreaming: false
  },
  {
    id: "fake-unavailable-model-123",
    provider: "nvidia",
    capabilities: ["test-fallback"],
    modalities: ["text"],
    priority: 1,
    enabled: true,
    contextSize: 4096,
    reasoningLevel: 5,
    codingLevel: 5,
    visionLevel: 0,
    speedLevel: 5,
    reliabilityScore: 5,
    costTier: 1,
    supportsTools: false,
    supportsStreaming: false
  },
  {
    id: "nvidia/llama-3.1-nemoguard-8b-content-safety",
    provider: "nvidia",
    capabilities: ["security"],
    modalities: ["text"],
    priority: 1,
    enabled: true,
    contextSize: 8192,
    reasoningLevel: 3,
    codingLevel: 0,
    visionLevel: 0,
    speedLevel: 9,
    reliabilityScore: 9,
    costTier: 1,
    supportsTools: false,
    supportsStreaming: false
  },
  {
    id: "meta/llama-guard-4-12b",
    provider: "nvidia",
    capabilities: ["security"],
    modalities: ["text"],
    priority: 2,
    enabled: true,
    contextSize: 8192,
    reasoningLevel: 3,
    codingLevel: 0,
    visionLevel: 0,
    speedLevel: 8,
    reliabilityScore: 9,
    costTier: 1,
    supportsTools: false,
    supportsStreaming: false
  }
];
