import { BadgeCheck, MapPin, ShieldCheck, Sparkles } from "lucide-react";
import { redirect } from "next/navigation";

import { PortalShell } from "@/components/portal/portal-shell";
import { prisma } from "@/lib/db";
import { getCurrentIdentity } from "@/modules/auth/session";

export default async function SaathiProfilePage() {
  const identity = await getCurrentIdentity();
  if (!identity?.roles.includes("SITTER")) redirect("/login?returnTo=/saathi/profile");
  const sitter = await prisma.sitterProfile.findUnique({ where: { userId: identity.id }, include: { verifications: { orderBy: { checkedAt: "desc" } }, permissions: { include: { serviceType: { select: { name: true } } }, orderBy: { serviceType: { name: "asc" } } } } });
  if (!sitter) redirect("/become-a-saathi");
  const passed = sitter.verifications.filter((item) => item.status === "PASSED").length;
  const granted = sitter.permissions.filter((item) => item.status === "ACTIVE").length;
  return <PortalShell mode="saathi" displayName={identity.displayName} metrics={[sitter.status.replaceAll("_", " "), `${passed} passed verification${passed === 1 ? "" : "s"}`, `${granted} service permission${granted === 1 ? "" : "s"}`]}><section className="mt-5 overflow-hidden rounded-5xl border border-indigo/10 bg-gradient-to-br from-[#f3eafa] via-paper to-[#fff0e8] p-7 shadow-soft sm:p-10"><div className="flex flex-col gap-6 sm:flex-row sm:items-center"><span className="flex h-24 w-24 items-center justify-center rounded-[2rem] bg-indigo font-display text-4xl font-semibold text-paper shadow-soft">{identity.displayName.slice(0, 1).toUpperCase()}</span><div><p className="eyebrow">Saathi profile</p><h2 className="mt-3 font-display text-5xl font-semibold tracking-[-0.05em]">{identity.displayName}</h2><p className="mt-3 flex items-center gap-2 text-sm text-ink/52"><MapPin className="h-4 w-4 text-coral" />{sitter.serviceLocality ?? "Service locality pending"} · {sitter.yearsExperience} years experience</p></div></div>{sitter.bio && <p className="mt-7 max-w-3xl text-lg leading-8 text-ink/58">{sitter.bio}</p>}</section><div className="mt-5 grid gap-5 lg:grid-cols-2"><section className="rounded-4xl border border-indigo/10 bg-paper p-6 shadow-lifted"><p className="flex items-center gap-2 text-sm font-bold"><ShieldCheck className="h-5 w-5 text-leaf" />Verification record</p><div className="mt-5 grid gap-2">{sitter.verifications.length ? sitter.verifications.map((item) => <div key={item.id} className="flex items-center justify-between rounded-2xl bg-cream/55 p-4"><div><p className="text-sm font-bold">{item.publicLabel ?? item.type.replaceAll("_", " ")}</p><p className="mt-1 text-xs text-ink/40">{item.checkedAt ? `Checked ${item.checkedAt.toLocaleDateString("en-IN")}` : "Review pending"}</p></div><span className={`rounded-full px-3 py-1 text-[0.62rem] font-bold ${item.status === "PASSED" ? "bg-leaf/10 text-leaf" : "bg-saffron/20 text-ink"}`}>{item.status}</span></div>) : <p className="text-sm text-ink/48">No verification records yet.</p>}</div></section><section className="rounded-4xl border border-indigo/10 bg-paper p-6 shadow-lifted"><p className="flex items-center gap-2 text-sm font-bold"><BadgeCheck className="h-5 w-5 text-indigo" />Service permissions</p><div className="mt-5 grid gap-2">{sitter.permissions.length ? sitter.permissions.map((item) => <div key={item.id} className="flex items-center justify-between rounded-2xl bg-cream/55 p-4"><p className="text-sm font-bold">{item.serviceType.name}</p><span className="rounded-full bg-indigo/10 px-3 py-1 text-[0.62rem] font-bold text-indigo">{item.status}</span></div>) : <p className="text-sm text-ink/48">No service permission is active yet.</p>}</div><p className="mt-5 flex items-start gap-2 text-xs leading-5 text-ink/42"><Sparkles className="mt-0.5 h-4 w-4 shrink-0 text-coral" />Only reviewed evidence is shown. Approval is never universal across services.</p></section></div></PortalShell>;
}
