import { Gift, HeartHandshake, Sparkles } from "lucide-react";
import { redirect } from "next/navigation";

import { PortalShell } from "@/components/portal/portal-shell";
import { prisma } from "@/lib/db";
import { getCurrentIdentity } from "@/modules/auth/session";

export default async function ReferralProtocolPage() {
  const identity = await getCurrentIdentity();
  if (!identity?.roles.includes("CUSTOMER")) redirect("/login?returnTo=/customer/referrals");
  const referrals = await prisma.referral.findMany({ where: { referrerId: identity.id }, orderBy: { createdAt: "desc" }, include: { referred: { select: { displayName: true } } } });
  const rewarded = referrals.filter((item) => Boolean(item.rewardedAt)).length;
  const qualified = referrals.filter((item) => Boolean(item.qualifiedAt)).length;
  return <PortalShell mode="customer" displayName={identity.displayName} metrics={[`${referrals.length} invitation${referrals.length === 1 ? "" : "s"}`, `${qualified} qualified`, `${rewarded} rewarded`]}><div className="mt-5 grid gap-5 lg:grid-cols-[0.8fr_1.2fr]"><section className="relative overflow-hidden rounded-5xl bg-[#2f2032] p-7 text-paper shadow-soft sm:p-9"><div className="absolute -right-14 -top-14 h-48 w-48 rounded-full bg-coral/20 blur-3xl" /><Gift className="h-8 w-8 text-saffron" /><p className="mt-10 text-[0.62rem] font-bold uppercase tracking-[0.2em] text-paper/50">Referral protocol</p><h2 className="mt-3 font-display text-4xl font-semibold tracking-[-0.04em]">Thoughtful care is worth sharing.</h2><p className="mt-4 text-sm leading-6 text-paper/60">Rewards are released only after a referred friend completes the qualifying action. Codes never bypass identity, safety or payment controls.</p></section><section className="rounded-4xl border border-indigo/10 bg-paper p-6 shadow-lifted"><p className="eyebrow">Invitation ledger</p><div className="mt-5 grid gap-3">{referrals.length ? referrals.map((referral) => <article key={referral.id} className="rounded-3xl bg-cream/55 p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-[0.14em] text-coral">Code · {referral.code}</p><h3 className="mt-2 font-display text-2xl font-semibold">{referral.referred?.displayName ?? "Invitation waiting"}</h3></div><span className="rounded-full bg-indigo/10 px-3 py-1.5 text-xs font-bold text-indigo">{referral.status}</span></div><p className="mt-3 text-xs text-ink/42">Created {referral.createdAt.toLocaleDateString("en-IN", { dateStyle: "medium" })}{referral.rewardedAt ? ` · rewarded ${referral.rewardedAt.toLocaleDateString("en-IN", { dateStyle: "medium" })}` : ""}</p></article>) : <div className="rounded-4xl border border-dashed border-indigo/15 p-9 text-center"><HeartHandshake className="mx-auto h-10 w-10 text-indigo/35" /><h3 className="mt-4 font-display text-3xl font-semibold">No invitations yet.</h3><p className="mt-2 text-sm leading-6 text-ink/48">A referral code will appear here when an authorised referral campaign is active for your account.</p><p className="mt-5 flex items-center justify-center gap-2 text-xs font-bold text-leaf"><Sparkles className="h-4 w-4" />No hidden or provisional rewards</p></div>}</div></section></div></PortalShell>;
}
