import { CalendarDays, CheckCircle2, CircleDot, Clock3 } from "lucide-react";
import Link from "next/link";
import { notFound, redirect } from "next/navigation";

import { PortalShell } from "@/components/portal/portal-shell";
import { buttonVariants } from "@/components/ui/button";
import { prisma } from "@/lib/db";
import { getCurrentIdentity } from "@/modules/auth/session";

export default async function CareTimelinePage({ params }: { params: Promise<{ id: string }> }) {
  const identity = await getCurrentIdentity(); const { id } = await params;
  if (!identity?.roles.includes("CUSTOMER")) redirect(`/login?returnTo=/bookings/${id}/timeline`);
  const booking = await prisma.booking.findFirst({ where: { id, customerId: identity.id }, include: { pet: { select: { name: true } }, serviceType: { select: { name: true } }, statusHistory: { orderBy: { createdAt: "asc" } }, serviceEvents: { orderBy: { occurredAt: "asc" } }, reports: { orderBy: { submittedAt: "asc" }, select: { id: true, version: true, submittedAt: true, reviewStatus: true } } } });
  if (!booking) notFound();
  const timeline = [...booking.statusHistory.map((item) => ({ id: item.id, at: item.createdAt, label: item.toState.replaceAll("_", " "), detail: item.reason ?? "Booking state recorded", tone: "state" as const })), ...booking.serviceEvents.map((item) => ({ id: item.id, at: item.occurredAt, label: item.type.replaceAll("_", " "), detail: item.notes ?? "Service milestone recorded", tone: "event" as const })), ...booking.reports.map((item) => ({ id: item.id, at: item.submittedAt, label: `REPORT V${item.version} ${item.reviewStatus.replaceAll("_", " ")}`, detail: "Care report committed to the booking", tone: "report" as const }))].sort((a, b) => a.at.getTime() - b.at.getTime());
  return <PortalShell mode="customer" displayName={identity.displayName} metrics={[booking.status.replaceAll("_", " "), `${booking.statusHistory.length} state changes`, `${booking.serviceEvents.length} service events`]}><section className="mt-5 rounded-5xl border border-indigo/10 bg-paper p-6 shadow-soft sm:p-9"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="eyebrow">Care protocol timeline</p><h1 className="mt-4 font-display text-4xl font-semibold tracking-[-0.04em] sm:text-5xl">{booking.serviceType.name} for {booking.pet.name}</h1><p className="mt-3 flex items-center gap-2 text-sm text-ink/48"><CalendarDays className="h-4 w-4 text-coral" />{booking.scheduledStart.toLocaleString("en-IN", { dateStyle: "full", timeStyle: "short" })}</p></div><Link href={`/bookings/${booking.id}`} className={buttonVariants({ variant: "outline" })}>Booking overview</Link></div><div className="relative mt-10 grid gap-0 before:absolute before:bottom-6 before:left-[1.18rem] before:top-6 before:w-px before:bg-indigo/15">{timeline.length ? timeline.map((item) => <article key={`${item.tone}-${item.id}`} className="relative grid grid-cols-[2.5rem_1fr] gap-4 pb-7"><span className={`relative z-10 flex h-10 w-10 items-center justify-center rounded-full border-4 border-paper ${item.tone === "report" ? "bg-coral text-paper" : item.tone === "event" ? "bg-leaf text-paper" : "bg-indigo/10 text-indigo"}`}>{item.tone === "report" ? <CheckCircle2 className="h-4 w-4" /> : item.tone === "event" ? <CircleDot className="h-4 w-4" /> : <Clock3 className="h-4 w-4" />}</span><div className="rounded-3xl bg-cream/55 p-5"><div className="flex flex-wrap items-center justify-between gap-2"><h2 className="text-sm font-bold uppercase tracking-[0.12em]">{item.label}</h2><time className="text-xs text-ink/40">{item.at.toLocaleString("en-IN", { dateStyle: "medium", timeStyle: "short" })}</time></div><p className="mt-2 text-sm leading-6 text-ink/50">{item.detail}</p></div></article>) : <p className="rounded-3xl border border-dashed border-indigo/15 p-8 text-center text-sm text-ink/48">The timeline will begin when the request is recorded.</p>}</div></section></PortalShell>;
}
