import { Bell, Headphones, Inbox } from "lucide-react";
import { redirect } from "next/navigation";

import { PortalShell } from "@/components/portal/portal-shell";
import { prisma } from "@/lib/db";
import { getCurrentIdentity } from "@/modules/auth/session";

export default async function CustomerProtocolInboxPage() {
  const identity = await getCurrentIdentity();
  if (!identity?.roles.includes("CUSTOMER")) redirect("/login?returnTo=/customer/inbox");
  const [notices, cases] = await Promise.all([prisma.notificationOutbox.findMany({ where: { userId: identity.id, status: { not: "CANCELLED" } }, orderBy: { scheduledAt: "desc" }, take: 30, select: { id: true, templateKey: true, status: true, scheduledAt: true } }), prisma.supportCase.findMany({ where: { userId: identity.id }, orderBy: { updatedAt: "desc" }, take: 20, select: { id: true, reference: true, subject: true, status: true, updatedAt: true, resolution: true } })]);
  return <PortalShell mode="customer" displayName={identity.displayName} metrics={[`${notices.length} care update${notices.length === 1 ? "" : "s"}`, `${cases.filter((item) => item.status !== "CLOSED").length} open support case${cases.filter((item) => item.status !== "CLOSED").length === 1 ? "" : "s"}`, "No unstructured chat"]}><div className="mt-5 grid gap-5 lg:grid-cols-2"><section className="rounded-4xl border border-indigo/10 bg-paper p-6 shadow-lifted"><p className="eyebrow">Protocol inbox</p><h2 className="mt-3 font-display text-3xl font-semibold">Care updates</h2><p className="mt-2 text-sm leading-6 text-ink/48">Status-led updates stay attached to authenticated care records.</p><div className="mt-5 grid gap-3">{notices.length ? notices.map((notice) => <article key={notice.id} className="rounded-3xl bg-cream/55 p-4"><div className="flex items-start gap-3"><span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-2xl bg-indigo/10 text-indigo"><Bell className="h-4 w-4" /></span><div><p className="text-sm font-bold">{notice.templateKey.replaceAll(".", " · ").replaceAll("_", " ")}</p><p className="mt-1 text-xs text-ink/42">{notice.status} · {notice.scheduledAt.toLocaleString("en-IN", { dateStyle: "medium", timeStyle: "short" })}</p></div></div></article>) : <Empty icon={Inbox} title="No care updates yet." copy="Booking, payment, report and safety notices will appear here." />}</div></section><section className="rounded-4xl border border-indigo/10 bg-gradient-to-br from-[#f3eafa] to-paper p-6 shadow-lifted"><p className="eyebrow">Supported conversations</p><h2 className="mt-3 font-display text-3xl font-semibold">Support threads</h2><p className="mt-2 text-sm leading-6 text-ink/48">Free-form chat is not presented as a substitute for booking, incident or support records.</p><div className="mt-5 grid gap-3">{cases.length ? cases.map((item) => <article key={item.id} className="rounded-3xl bg-paper/85 p-4"><div className="flex items-center justify-between gap-3"><p className="text-xs font-bold uppercase tracking-[0.13em] text-coral">{item.reference}</p><span className="rounded-full bg-indigo/10 px-3 py-1 text-[0.62rem] font-bold text-indigo">{item.status.replaceAll("_", " ")}</span></div><p className="mt-3 font-bold">{item.subject}</p><p className="mt-1 text-xs text-ink/42">Updated {item.updatedAt.toLocaleString("en-IN", { dateStyle: "medium", timeStyle: "short" })}</p>{item.resolution && <p className="mt-3 rounded-2xl bg-cream/55 p-3 text-sm leading-6 text-ink/52">{item.resolution}</p>}</article>) : <Empty icon={Headphones} title="No support threads." copy="A submitted support case will create a traceable conversation here." />}</div></section></div></PortalShell>;
}

function Empty({ icon: Icon, title, copy }: { icon: typeof Inbox; title: string; copy: string }) { return <div className="rounded-3xl border border-dashed border-indigo/15 p-8 text-center"><Icon className="mx-auto h-8 w-8 text-indigo/30" /><h3 className="mt-4 font-display text-2xl font-semibold">{title}</h3><p className="mt-2 text-sm leading-6 text-ink/45">{copy}</p></div>; }
